name: Zo-0-17-Auto-Renew-Workflow

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. 拉取代码
        uses: actions/checkout@v3

      - name: 2. 安装 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. 安装项目依赖
        run: |
          pip install pyrogram tgcrypto playwright requests
          playwright install --with-deps chromium
          
      - name: 执行自动化脚本
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TG_STRING_SESSION: ${{ secrets.TG_STRING_SESSION }}
          WENPASSWORD: ${{ secrets.WENPASSWORD }}
          TELEGRAM_ACCOUNT_ID: ${{ secrets.TELEGRAM_ACCOUNT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN_A }}
          MY_CHAT_ID: ${{ secrets.MY_CHAT_ID_A }}
        run: |
          curl -fsSL \
            -H "Authorization: Bearer ${MY_GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.raw" \
            -o Z0.py \
            "https://api.github.com/repos/akina005/hax-host2play/contents/Z0.py?ref=main"
          python Z0.py
